package Db.Components.rmi.iiop.interfaces;


import java.rmi.Remote;
import java.rmi.RemoteException;

/**
* Db/Components/corba/DatabaseManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

public interface DatabaseManager extends Remote
{
  String createDatabase (String name) throws RemoteException;
  String[] getDatabaseNames () throws RemoteException;
  String getDatabase (String name) throws RemoteException;
  boolean isExists (String name) throws RemoteException;
  void deleteDatabase (String name) throws RemoteException;
  void renameDatabase (String oldName, String newName) throws RemoteException;
} // interface DatabaseManagerOperations
