package Db.Components.rmi.iiop.interfaces;


import java.rmi.Remote;
import java.rmi.RemoteException;

/**
* Db/Components/corba/DatabaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

public interface Database extends Remote
{
  boolean addTable (String name) throws RemoteException;
  String[] getTableNames () throws RemoteException;
  String getName () throws RemoteException;
  String getTable (String name) throws RemoteException;
  void renameTable (String oldName, String newName) throws RemoteException;
  void deleteTable (String name) throws RemoteException;
  void save () throws RemoteException;
} // interface DatabaseOperations
