package Db.Components.rmi.iiop.interfaces;

import java.rmi.Remote;
import java.rmi.RemoteException;

/**
* Db/Components/corba/TableOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

public interface Table extends Remote
{
  DbType[][] getRows () throws RemoteException;
  ColumnHeader[] getColumns () throws RemoteException;
  String getName () throws RemoteException;
  void setName (String name) throws RemoteException;
  DbType[] insertRow (String[] data) throws RemoteException;
  boolean addColumn (String name, String type) throws RemoteException;
  ColumnHeader getColumn (String name) throws RemoteException;
  void setData (String value, String columnHeader, int rowIndex) throws RemoteException;
} // interface TableOperations
