package Db.Components.corba;


/**
* Db/Components/corba/ColumnHeader.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

public final class ColumnHeader implements org.omg.CORBA.portable.IDLEntity
{
  public String type = null;
  public String name = null;
  public String title = null;

  public ColumnHeader ()
  {
  } // ctor

  public ColumnHeader (String _type, String _name, String _title)
  {
    type = _type;
    name = _name;
    title = _title;
  } // ctor

} // class ColumnHeader
