package Db.Components.corba;

/**
* Db/Components/corba/DatabaseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

public final class DatabaseHolder implements org.omg.CORBA.portable.Streamable
{
  public Db.Components.corba.Database value = null;

  public DatabaseHolder ()
  {
  }

  public DatabaseHolder (Db.Components.corba.Database initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Db.Components.corba.DatabaseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Db.Components.corba.DatabaseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Db.Components.corba.DatabaseHelper.type ();
  }

}
