package Db.Components.corba;


/**
* Db/Components/corba/DatabaseManagerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

abstract public class DatabaseManagerHelper
{
  private static String  _id = "IDL:Db/Components/corba/DatabaseManager:1.0";

  public static void insert (org.omg.CORBA.Any a, Db.Components.corba.DatabaseManager that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Db.Components.corba.DatabaseManager extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Db.Components.corba.DatabaseManagerHelper.id (), "DatabaseManager");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Db.Components.corba.DatabaseManager read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DatabaseManagerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Db.Components.corba.DatabaseManager value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Db.Components.corba.DatabaseManager narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Db.Components.corba.DatabaseManager)
      return (Db.Components.corba.DatabaseManager)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Db.Components.corba._DatabaseManagerStub stub = new Db.Components.corba._DatabaseManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Db.Components.corba.DatabaseManager unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Db.Components.corba.DatabaseManager)
      return (Db.Components.corba.DatabaseManager)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Db.Components.corba._DatabaseManagerStub stub = new Db.Components.corba._DatabaseManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
