package Db.Components.corba;


/**
* Db/Components/corba/DatabaseManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

public interface DatabaseManagerOperations 
{
  String createDatabase (String name);
  String[] getDatabaseNames ();
  String getDatabase (String name);
  boolean isExists (String name);
  void deleteDatabase (String name);
  void renameDatabase (String oldName, String newName);
} // interface DatabaseManagerOperations
