package Db.Components.corba;


/**
* Db/Components/corba/DatabaseHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

abstract public class DatabaseHelper
{
  private static String  _id = "IDL:Db/Components/corba/Database:1.0";

  public static void insert (org.omg.CORBA.Any a, Db.Components.corba.Database that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Db.Components.corba.Database extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Db.Components.corba.DatabaseHelper.id (), "Database");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Db.Components.corba.Database read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DatabaseStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Db.Components.corba.Database value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Db.Components.corba.Database narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Db.Components.corba.Database)
      return (Db.Components.corba.Database)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Db.Components.corba._DatabaseStub stub = new Db.Components.corba._DatabaseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Db.Components.corba.Database unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Db.Components.corba.Database)
      return (Db.Components.corba.Database)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Db.Components.corba._DatabaseStub stub = new Db.Components.corba._DatabaseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
