package Db.Components.corba;


/**
* Db/Components/corba/DatabaseManagerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

public abstract class DatabaseManagerPOA extends org.omg.PortableServer.Servant
 implements Db.Components.corba.DatabaseManagerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createDatabase", new java.lang.Integer (0));
    _methods.put ("getDatabaseNames", new java.lang.Integer (1));
    _methods.put ("getDatabase", new java.lang.Integer (2));
    _methods.put ("isExists", new java.lang.Integer (3));
    _methods.put ("deleteDatabase", new java.lang.Integer (4));
    _methods.put ("renameDatabase", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Db/Components/corba/DatabaseManager/createDatabase
       {
         String name = in.read_string ();
         String $result = null;
         $result = this.createDatabase (name);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Db/Components/corba/DatabaseManager/getDatabaseNames
       {
         String $result[] = null;
         $result = this.getDatabaseNames ();
         out = $rh.createReply();
         Db.Components.corba.ListStringHelper.write (out, $result);
         break;
       }

       case 2:  // Db/Components/corba/DatabaseManager/getDatabase
       {
         String name = in.read_string ();
         String $result = null;
         $result = this.getDatabase (name);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // Db/Components/corba/DatabaseManager/isExists
       {
         String name = in.read_string ();
         boolean $result = false;
         $result = this.isExists (name);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // Db/Components/corba/DatabaseManager/deleteDatabase
       {
         String name = in.read_string ();
         this.deleteDatabase (name);
         out = $rh.createReply();
         break;
       }

       case 5:  // Db/Components/corba/DatabaseManager/renameDatabase
       {
         String oldName = in.read_string ();
         String newName = in.read_string ();
         this.renameDatabase (oldName, newName);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Db/Components/corba/DatabaseManager:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DatabaseManager _this() 
  {
    return DatabaseManagerHelper.narrow(
    super._this_object());
  }

  public DatabaseManager _this(org.omg.CORBA.ORB orb) 
  {
    return DatabaseManagerHelper.narrow(
    super._this_object(orb));
  }


} // class DatabaseManagerPOA
