package Db.Components.corba;


/**
* Db/Components/corba/DatabasePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

public abstract class DatabasePOA extends org.omg.PortableServer.Servant
 implements Db.Components.corba.DatabaseOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addTable", new java.lang.Integer (0));
    _methods.put ("getTableNames", new java.lang.Integer (1));
    _methods.put ("getName", new java.lang.Integer (2));
    _methods.put ("getTable", new java.lang.Integer (3));
    _methods.put ("renameTable", new java.lang.Integer (4));
    _methods.put ("deleteTable", new java.lang.Integer (5));
    _methods.put ("save", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Db/Components/corba/Database/addTable
       {
         String name = in.read_string ();
         boolean $result = false;
         $result = this.addTable (name);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Db/Components/corba/Database/getTableNames
       {
         String $result[] = null;
         $result = this.getTableNames ();
         out = $rh.createReply();
         Db.Components.corba.ListStringHelper.write (out, $result);
         break;
       }

       case 2:  // Db/Components/corba/Database/getName
       {
         String $result = null;
         $result = this.getName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // Db/Components/corba/Database/getTable
       {
         String name = in.read_string ();
         String $result = null;
         $result = this.getTable (name);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // Db/Components/corba/Database/renameTable
       {
         String oldName = in.read_string ();
         String newName = in.read_string ();
         this.renameTable (oldName, newName);
         out = $rh.createReply();
         break;
       }

       case 5:  // Db/Components/corba/Database/deleteTable
       {
         String name = in.read_string ();
         this.deleteTable (name);
         out = $rh.createReply();
         break;
       }

       case 6:  // Db/Components/corba/Database/save
       {
         this.save ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Db/Components/corba/Database:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Database _this() 
  {
    return DatabaseHelper.narrow(
    super._this_object());
  }

  public Database _this(org.omg.CORBA.ORB orb) 
  {
    return DatabaseHelper.narrow(
    super._this_object(orb));
  }


} // class DatabasePOA
