package Db.Components.corba;


/**
* Db/Components/corba/DatabaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

public interface DatabaseOperations 
{
  boolean addTable (String name);
  String[] getTableNames ();
  String getName ();
  String getTable (String name);
  void renameTable (String oldName, String newName);
  void deleteTable (String name);
  void save ();
} // interface DatabaseOperations
