package Db.Components.corba;

/**
* Db/Components/corba/DbTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

public final class DbTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public Db.Components.corba.DbType value = null;

  public DbTypeHolder ()
  {
  }

  public DbTypeHolder (Db.Components.corba.DbType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Db.Components.corba.DbTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Db.Components.corba.DbTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Db.Components.corba.DbTypeHelper.type ();
  }

}
