package Db.Components.corba;


/**
* Db/Components/corba/ListColumnHeaderHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

abstract public class ListColumnHeaderHelper
{
  private static String  _id = "IDL:Db/Components/corba/ListColumnHeader:1.0";

  public static void insert (org.omg.CORBA.Any a, Db.Components.corba.ColumnHeader[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Db.Components.corba.ColumnHeader[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Db.Components.corba.ColumnHeaderHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Db.Components.corba.ListColumnHeaderHelper.id (), "ListColumnHeader", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Db.Components.corba.ColumnHeader[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Db.Components.corba.ColumnHeader value[] = null;
    int _len0 = istream.read_long ();
    value = new Db.Components.corba.ColumnHeader[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Db.Components.corba.ColumnHeaderHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Db.Components.corba.ColumnHeader[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Db.Components.corba.ColumnHeaderHelper.write (ostream, value[_i0]);
  }

}
