package Db.Components.corba;


/**
* Db/Components/corba/ListStringHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

public final class ListStringHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ListStringHolder ()
  {
  }

  public ListStringHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Db.Components.corba.ListStringHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Db.Components.corba.ListStringHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Db.Components.corba.ListStringHelper.type ();
  }

}
