package Db.Components.corba;


/**
* Db/Components/corba/TableOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

public interface TableOperations 
{
  Db.Components.corba.DbType[][] getRows ();
  Db.Components.corba.ColumnHeader[] getColumns ();
  String getName ();
  void setName (String name);
  Db.Components.corba.DbType[] insertRow (String[] data);
  boolean addColumn (String name, String type);
  Db.Components.corba.ColumnHeader getColumn (String name);
  void setData (String value, String columnHeader, int rowIndex);
} // interface TableOperations
