package Db.Components.corba;


/**
* Db/Components/corba/TablePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./DatabaseManager.idl
* 1 ноября 2017 г. 9:39:50 EET
*/

public abstract class TablePOA extends org.omg.PortableServer.Servant
 implements Db.Components.corba.TableOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getRows", new java.lang.Integer (0));
    _methods.put ("getColumns", new java.lang.Integer (1));
    _methods.put ("getName", new java.lang.Integer (2));
    _methods.put ("setName", new java.lang.Integer (3));
    _methods.put ("insertRow", new java.lang.Integer (4));
    _methods.put ("addColumn", new java.lang.Integer (5));
    _methods.put ("getColumn", new java.lang.Integer (6));
    _methods.put ("setData", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Db/Components/corba/Table/getRows
       {
         Db.Components.corba.DbType $result[][] = null;
         $result = this.getRows ();
         out = $rh.createReply();
         Db.Components.corba.ListRowHelper.write (out, $result);
         break;
       }

       case 1:  // Db/Components/corba/Table/getColumns
       {
         Db.Components.corba.ColumnHeader $result[] = null;
         $result = this.getColumns ();
         out = $rh.createReply();
         Db.Components.corba.ListColumnHeaderHelper.write (out, $result);
         break;
       }

       case 2:  // Db/Components/corba/Table/getName
       {
         String $result = null;
         $result = this.getName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // Db/Components/corba/Table/setName
       {
         String name = in.read_string ();
         this.setName (name);
         out = $rh.createReply();
         break;
       }

       case 4:  // Db/Components/corba/Table/insertRow
       {
         String data[] = Db.Components.corba.ListStringHelper.read (in);
         Db.Components.corba.DbType $result[] = null;
         $result = this.insertRow (data);
         out = $rh.createReply();
         Db.Components.corba.RowHelper.write (out, $result);
         break;
       }

       case 5:  // Db/Components/corba/Table/addColumn
       {
         String name = in.read_string ();
         String type = in.read_string ();
         boolean $result = false;
         $result = this.addColumn (name, type);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // Db/Components/corba/Table/getColumn
       {
         String name = in.read_string ();
         Db.Components.corba.ColumnHeader $result = null;
         $result = this.getColumn (name);
         out = $rh.createReply();
         Db.Components.corba.ColumnHeaderHelper.write (out, $result);
         break;
       }

       case 7:  // Db/Components/corba/Table/setData
       {
         String value = in.read_string ();
         String columnHeader = in.read_string ();
         int rowIndex = in.read_long ();
         this.setData (value, columnHeader, rowIndex);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Db/Components/corba/Table:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Table _this() 
  {
    return TableHelper.narrow(
    super._this_object());
  }

  public Table _this(org.omg.CORBA.ORB orb) 
  {
    return TableHelper.narrow(
    super._this_object(orb));
  }


} // class TablePOA
